services:
  fc3-codeflix-backend-admin-catalogo-de-videos:
    # O . em build: . é relativo ao local onde está o arquivo docker-compose.yml, não ao terminal.
    build: 
      context: .
      dockerfile: Dockerfile
    # esse arquivo precisa da permissão chmod a+x .docker/start.sh
    command: ./docker/.docker/start.sh
    ports:
      - 3000:3000
    # relativo ao docker compose
    volumes:
      - ../:/home/node/app
      # Por padrão, o container não vem com o horário/fuso do host configurado corretamente.
      # Essas linhas sincronizam o horário do container com o host, evitando erro de expiração de JWT no SDK do Google Cloud por diferença de fuso horário.
      # OBS: Funciona apenas em ambientes Linux. No Windows seria preciso outra configuração para timezone, pois esses arquivos não existem.
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
  
  db-fc3-codeflix-backend-admin-catalogo-de-videos:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    # volumes:
    # - ./.docker/mysql:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
  fc3-codeflix-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      # porta da interface web exposta para o host
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    #volumes:
      # consigo salvar os dados das filas
      #- ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      #- ./rabbitmq_data:/var/lib/rabbitmq
    #tmpfs:
      #- /var/lib/rabbitmq
      #- /etc/rabbitmq